name: Build Unsigned APK and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build APK and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create local.properties
        run: |
          cat > local.properties << 'EOF'
          api_key=${{ secrets.TMDB_API_KEY }}
          base_url=https://api.themoviedb.org/3/
          base_image_url=https://image.tmdb.org/t/p/w500/
          EOF

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build unsigned APK
        run: ./gradlew assembleDebug --no-daemon --parallel

      - name: Rename APK with tag version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          cp app/build/outputs/apk/debug/app-debug.apk app-${TAG_NAME}-unsigned.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: app-${{ github.ref_name }}-unsigned.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
